create database empleados;
use empleados;

-- MySQL Script generated by MySQL Workbench

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleados` (
  `id` INT NOT NULL auto_increment,
  `full_name` VARCHAR(45) NOT NULL,
  `income` FLOAT NOT NULL,
  `department` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


insert into empleados(full_name, income, department)
values
      ("Anson Roper", 250.5, "abc"),
      ("Asphodel Brandybuck", 300, "aaa"),
      ("Isumbras Took", 125.3, "aaa"),
      ("Ivy Goodenough", 275, "abc"),
      ("Jago Boffin", 280, "abc"),
      ("Jessamine Boffin", 290, "ccc"),
      ("Lalia Clayhanger", 400, "bbb"),
      ("Largo Baggins", 300.4, "bbb"),  
      ("Merry Gardner", 190, "ccc"),
      ("Milo Burrows", 300, "ccc"),
      ("Mimosa Bunce", 180, "abc"),
      ("Pippin Gardner", 200, "ccc"),	
      ("Polo Baggins", 150, "bbb"),
      ("Sancho Proudfoot", 230, "bbb"),
      ("Sapphira Brockhouse", 380.7, "aaa"),
      ("Saradas Brandybuck", 195, "aaa"),
      ("Tanta Hornblower", 190, "ccc"),
      ("Theobald Bolger", 200, "aaa"),
      ("Tobold Hornblower", 300, "abc"),
      ("Togo Goodbody", 230, "bbb"),
      ("Tolman Cotton", 250, "bbb"),
      ("Tolman Gardner", 200, "aaa");
